# xxl-job
xxl:
  job:
    admin:
      addresses: http://s1.iocoder.cn:18079/
    executor:
      appname: pay-job-executor
      ip:
      port: 0
      logpath: /Users/yunai/logs/xxl-job/
      logretentiondays: 1
    accessToken:
